name: solid_products
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  http: ^0.13.5
  intl: ^0.17.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  chopper: ^8.1.0
  provider: ^6.1.5
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  chopper_generator: ^8.1.0


flutter:
  uses-material-design: true
